name: Seahub Dist CI

on:
  push:
    branches:
      - master
      - "13.0"

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - uses: actions/setup-node@v3
        with:
          node-version: "20.x"

      - name: gettext for django
        run: |
          sudo apt-get update --fix-missing
          sudo apt-get install gettext python3-wheel libjwt-dev libsasl2-dev libldap2-dev python3-cffi
          sudo rm -rf /usr/lib/python3/dist-packages/pytz/

      - name: Build dist branch
        run: |
          cd $GITHUB_WORKSPACE/tests/
          chmod +x github_actions_dist.sh
          ./github_actions_dist.sh
