name: Seahub Dist CI

on:
  push:
    branches:
      - master
      - "7.1"

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
        with:
          python-version: "3.x"
      - uses: actions/setup-node@v1
        with:
          node-version: "10.x"

      - name: gettext for django
        run: sudo apt-get install gettext

      - name: Build dist branch
        run: |
          cd $GITHUB_WORKSPACE/tests/ 
          chmod +x github_actions_dist.sh 
          ./github_actions_dist.sh
